name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - name: Cake Action
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: Release
        cake-bootstrap: true
      env:
        QUAY_USER: ${{secrets.QUAY_USER}}
        QUAY_TOKEN: ${{secrets.QUAY_TOKEN}}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          dist/packages/linux-x64/*
          dist/archive/*.zip
          dist/publish/console/**/*.exe
        body: |
          Check [the releases docs](https://azurite.app/blog/releases/) for full information on updates and changes.
        draft: false
        prerelease: true
        name: Release ${{ github.ref }}