name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - name: Cake Action
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: Publish-Docker-Image
        cake-bootstrap: true
      env:
        QUAY_USER: ${{secrets.QUAY_USER}}
        QUAY_TOKEN: ${{secrets.QUAY_TOKEN}}
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Check [the releases docs](https://azurite.app/blog/releases/) for full information on updates and changes.
        draft: false
        prerelease: true
